
#==================================================#
# FIBER-seq analysis
#==================================================#

# Reanylse the FIBER-seq data generated by Jonas Koeppel

#================================#
# Set up environement

setwd("/lustre/scratch126/gengen/projects_v2/escramble/001_007_OTX2/Manuscripts/OTX2")

packages = c('dplyr', 'tidyr', 'ggplot2', 'scales', 'patchwork', 'rtracklayer', 'GenomicRanges', 'data.table', 'rstatix',
             'BSgenome.Hsapiens.UCSC.hg38')
for(p in packages) {
  library(p, character.only = TRUE, verbose = FALSE, quietly = TRUE)
  cat(p, "version:", as.character(packageVersion(p)), "\n")
}

#================================#
# Backup

cd /lustre/scratch126/gengen/projects_v2/escramble
git add ./001_007_OTX2/Manuscripts/OTX2/Revision_R_codes/008_fiber_seq_v2_1.R
git add ./001_007_OTX2/Manuscripts/OTX2/Revision_R_codes/008_fiber_seq/bw
git add ./001_007_OTX2/Manuscripts/OTX2/Revision_R_codes/008_fiber_seq/rplots
git commit -m "Last update committed on $(date +'%D %r')"
git push

#================================#
# Load and format raw data

fiber.seq.df <- read.csv("./Revision_R_codes/008_fiber_seq/raw_data/Fiberseq_enhancer_scramble.tsv", sep = "\t")

fiber.seq.df <- fiber.seq.df %>% filter(name %in% c("No sv evidence", "wildtype", "∆R123", "∆R4", "∆R5")) %>% 
  mutate(name = case_when(name == "No sv evidence" ~ "no.sv",
                          name == "wildtype" ~ "WT",
                          name == "∆R123" ~ "R123",
                          name == "∆R4" ~ "R4",
                          name == "∆R5" ~ "R5")) 

#================================#
# Compute base composition of ROI in 50 nt bins

# Tile the region of interest into 50 nt bins
bin <- 50
roi.gr <- GRanges(seqnames = "chr14", ranges = IRanges(start = min(fiber.seq.df$start), end = max(fiber.seq.df$end)))
roi.tile.gr <- tile(roi.gr, width = bin) %>% unlist()

# Compute the numbers of A in each bin
genome <- BSgenome.Hsapiens.UCSC.hg38
roi.tile.gr$A_count <- letterFrequency(getSeq(genome, roi.tile.gr), "A")

#================================#
# Binarise m6A signal

fiber.seq.bin.df <- fiber.seq.df %>%
  mutate(score = ifelse(perc_m6A > 0, 1, 0)) %>% 
  dplyr::select(chr, start, end, fiber, name, score)

#================================#
# Compute the average m6A signal in each bin

# Define a function to compute the percentage of m6A in each 100 nt bins per fiber

get_fibre_perc <- function(fr, fiber.seq.bin.df, roi.tile.gr) {
  gr <- fiber.seq.bin.df %>%
    filter(fiber == fr) %>%
    dplyr::select(seqnames = chr, start, end, score) %>%
    GRanges()
  
  # Retain all roi.tile.gr intervals, filling absent overlaps with 0
  overlap.df <- mergeByOverlaps(roi.tile.gr, gr) %>%
    as.data.frame() %>%
    group_by(
      seqnames = roi.tile.gr.seqnames,
      start    = roi.tile.gr.start,
      end      = roi.tile.gr.end
    ) %>%
    summarise(A = first(A), m6A = sum(score), .groups = "drop")
  
  as.data.frame(roi.tile.gr) %>%
    dplyr::select(seqnames, start, end) %>%
    left_join(overlap.df, by = c("seqnames", "start", "end")) %>%
    mutate(
      A        = replace_na(A, 0),
      m6A      = replace_na(m6A, 0),
      perc.m6A = ifelse(A == 0, 0, (m6A / A) * 100),
      fiber    = fr
    ) %>%
    left_join(
      fiber.seq.bin.df %>% dplyr::select(fiber, name) %>% distinct(),
      by = "fiber"
    )
}

# Apply

fiber.seq.perc.df <- fiber.seq.bin.df %>%
  pull(fiber) %>%
  unique() %>%
  lapply(get_fibre_perc, fiber.seq.bin.df = fiber.seq.bin.df, roi.tile.gr = roi.tile.gr) %>%
  bind_rows()

# Save table
write.table(fiber.seq.perc.df, "./Revision_R_codes/008_fiber_seq/tsv/fiber_seq_perc_m6A.tsv", sep = "\t", row.names = F, quote = F)

# Aggregate fiber data
fiber.seq.perc.summary.df <- fiber.seq.perc.df %>%
  group_by(name, seqnames, start, end) %>% summarise(m6A = mean(m6A, na.rm = T), perc.m6A = mean(perc.m6A), .groups = "drop")

# Save table
write.table(fiber.seq.perc.summary.df, "./Revision_R_codes/008_fiber_seq/tsv/fiber_seq_perc_m6A.aggregated.tsv", sep = "\t", row.names = F, quote = F)

#================================#
# Generate and export bigwigs

# Retrieve hg38 chromosome lengths for seqinfo
hg38.seqinfo <- seqinfo(BSgenome.Hsapiens.UCSC.hg38)

# Export function
export_bigwig <- function(sample.name, fiber.seq.perc.summary.df, seqinfo, output.dir = ".") {
  
  gr <- fiber.seq.perc.summary.df %>%
    filter(name == sample.name) %>%
    dplyr::select(seqnames, start, end, score = perc.m6A) %>% GRanges()
  
  # Assign hg38 seqinfo and drop any non-standard chromosomes
  seqlevels(gr, pruning.mode = "coarse") <- seqlevels(seqinfo)
  seqinfo(gr) <- seqinfo
  
  out.path <- file.path(output.dir, paste0(sample.name, ".bw"))
  export(gr, con = out.path, format = "bigWig")
  
  message("Exported: ", out.path)
  invisible(out.path)
}

# Apply across all unique names
output.dir <- "./Revision_R_codes/008_fiber_seq/bw"
dir.create(output.dir, showWarnings = FALSE)

fiber.seq.perc.summary.df %>%
  pull(name) %>%
  unique() %>%
  lapply(
    export_bigwig,
    fiber.seq.perc.summary.df = fiber.seq.perc.summary.df,
    seqinfo           = hg38.seqinfo,
    output.dir        = output.dir
  )

#==================================================#
# Signal quantification

# Define region of interest for quantification

# We quantify signal over the two R4 and R5 domains over peaks manually identified from the ATAC-seq and Fiber-seq data

# R4 peaks
# chr14:56,885,642-56,887,059
# chr14:56,888,218-56,888,777
# chr14:56,891,092-56,891,689
# chr14:56,894,527-56,895,236
# chr14:56,896,767-56,897,513

# R5 peaks
# chr14:56,899,903-56,900,201
# chr14:56,902,218-56,902,665
# chr14:56,903,077-56,903,636
# chr14:56,905,279-56,905,764

R4.peak.gr <- GRanges(seqnames = "chr14",
                      ranges = IRanges(start = c(56885642, 56888218, 56891092, 56894527, 56896767),
                                       end = c(56887059, 56888777, 56891689, 56895236, 56897513)),
                      strand = "*")
R4.peak.gr$domain <- "R4_domain"

R5.peak.gr <- GRanges(seqnames = "chr14",
                      ranges = IRanges(start = c(56899903, 56902218, 56903077, 56905279),
                                       end = c(56900201, 56902665, 56903636, 56905764)),
                      strand = "*")
R5.peak.gr$domain <- "R5_domain"

domain.gr <- c(R4.peak.gr, R5.peak.gr)

# Function to quantify signal over a domain

quantify_signal_func <- function(fiber.bw.path, domain_gr, sample) {
  fiber.bw <- import(fiber.bw.path, which = domain.gr)
  fiber.cpm.df <- mergeByOverlaps(fiber.bw, domain.gr) %>% as.data.frame() %>%
    dplyr::select(domain, score) %>% mutate(sample = sample)
}

# Compute

WT.fiber.df <- quantify_signal_func("./Revision_R_codes/008_fiber_seq/bw/WT.bw", domain.gr, "WT")
R123.fiber.df <- quantify_signal_func("./Revision_R_codes/008_fiber_seq/bw/R123.bw", domain.gr, "R123")
R4.fiber.df <- quantify_signal_func("./Revision_R_codes/008_fiber_seq/bw/R4.bw", domain.gr, "R4")
R5.fiber.df <- quantify_signal_func("./Revision_R_codes/008_fiber_seq/bw/R5.bw", domain.gr, "R5")

# Aggregate data
fiber.quant.df <- rbind(WT.fiber.df, R123.fiber.df, R4.fiber.df, R5.fiber.df) %>%
  mutate(sample = factor(sample, levels = c("WT", "R123", "R4", "R5")))

# Correct values for R4 and R5 domains
fiber.quant.df <- fiber.quant.df %>%
  mutate(score = case_when(
    sample == "R4" & domain == "R4_domain" ~ 0,
    sample == "R5" & domain == "R5_domain" ~ 0,
    TRUE ~ score
  ))

# Define a colour palette
sample_cols <- c(
  "WT"  = "#A7A8A9",
  "R123"  = "#55AC56",
  "R4"  = "#6B8EC9",
  "R5"  = "#A72A2B")

# Plot

fiber.quant.plot <- fiber.quant.df %>%
  ggplot(aes(x = sample, y = score, fill = sample)) +
  geom_boxplot(
    outliers = FALSE,
    width         = 0.6,
    linewidth     = 0.4,
    alpha         = 0.85
  ) +
  scale_fill_manual(values   = sample_cols) +
  scale_colour_manual(values = sample_cols) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.25))) +
  facet_wrap(~ domain, scales = "free_y",
             nrow = 1,
             labeller = as_labeller(c(
               "R4_domain" = "R4 domain",
               "R5_domain" = "R5 domain"
             ))) +
  xlab(NULL) +
  ylab("% adenine methylated") +
  theme_bw() +
  theme(
    aspect.ratio     = 1.5,
    panel.grid       = element_blank(),
    strip.text       = element_text(size = 9, face = "bold"),
    axis.text.x      = element_text(angle = 45, hjust = 1, size = 9),
    axis.text.y      = element_text(size = 8),
    axis.title.y     = element_text(size = 9),
    legend.position  = "none"
  )

# Compute stats

stat.test <- fiber.quant.df %>%
  group_by(domain) %>%
  wilcox_test(score ~ sample, ref.group = "WT") %>%
  adjust_pvalue(method = "BH") %>%
  add_significance(
    p.col       = "p.adj",
    cutpoints   = c(0, 0.001, 0.01, 0.05, 1),
    symbols     = c("***", "**", "*", "ns")
  ) %>%
  add_xy_position(x = "sample", dodge = 0.8)

# Compute fold change of mean signal relative to WT
fc <- fiber.quant.df %>%
  group_by(domain, sample) %>%
  summarise(median_score = median(score, na.rm = TRUE), .groups = "drop") %>%
  group_by(domain) %>%
  mutate(FC_vs_WT = median_score / median_score[sample == "WT"],
         log2FC_vs_WT = log2(median_score / median_score[sample == "WT"]))
fc

# Export plot

pdf("./Revision_R_codes/008_fiber_seq/rplots/fiber.quant.pdf", width=6, height=4, useDingbats=FALSE)
fiber.quant.plot
dev.off()

#==================================================#
# Plot a representative coverage plot from Fiber-seq

# Function transform a bigwig file into a dataframe with scores reported for a given step and a given interval

bigwig_to_table <- function(bigwig_file, chromosome, interval_start, interval_end, step) {
  # Check if the file exists
  if (!file.exists(bigwig_file)) {
    stop("The BigWig file does not exist.")
  }
  # Import the BigWig file for the specified chromosome and interval
  message("Reading BigWig file...")
  bw_data <- import(bigwig_file, which = GRanges(chromosome, IRanges(interval_start, interval_end)))
  # Convert BigWig data to a data.frame for easier handling
  bw_df <- as.data.frame(bw_data)
  # If no data exists in the interval, return an empty data frame
  if (nrow(bw_df) == 0) {
    message("No data found in the specified interval.")
    return(data.frame(Chromosome = character(), Start = integer(), End = integer(), Score = numeric()))
  }
  # Generate the intervals based on the provided step size
  starts <- seq(interval_start, interval_end, by = step)
  ends <- pmin(starts + step - 1, interval_end)
  # Initialize scores
  scores <- numeric(length(starts))
  # Iterate through each interval and calculate the mean score
  for (i in seq_along(starts)) {
    overlapping <- bw_df[bw_df$start <= ends[i] & bw_df$end >= starts[i], ]
    if (nrow(overlapping) > 0) {
      # Calculate the mean score for the overlapping region
      overlap_scores <- overlapping$score
      scores[i] <- mean(overlap_scores, na.rm = TRUE)
    } else {
      # Assign NA if no overlap
      scores[i] <- NA
    }
  }
  # Create the results table
  results <- data.frame(seqnames = chromosome, start = starts, end = ends, score = scores)
  return(results)
}

# Define region of interest
ROI.gr <- GRanges(seqnames = "chr14", ranges = IRanges(start = 56884635, end = 56907609))

# Load bigwig WT tracks and transform into df

WT.fiber.bw <- "./Revision_R_codes/008_fiber_seq/bw/WT.bw"
ROI.WT.fiber.df <- bigwig_to_table(WT.fiber.bw, "chr14", start(ROI.gr), end(ROI.gr), 100)

# Define markers to delineate the ROI

markers.df <- data.frame(
  name = c("R4_start", "R45_bound", "R5_end"),
  position = c(56884635, 56898377, 56907609)/1e6
)

# Plot the ATAC-seq signal across the locus for each sample

ROI.WT.fiber.plot <- ROI.WT.fiber.df %>%
  ggplot(aes(x = start / 1e6, y = score, fill = sample)) +
  geom_area(col = NA) +
  geom_line(linewidth = 0.25) +
  scale_fill_manual(values = sample_cols) +
  scale_colour_manual(values = "black") +
  xlab("Coordinate on chr14 [hg38]") +
  ylab("% adenine methylated") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = markers.df$position, linetype = "dashed") +
  theme_bw() +
  theme(aspect.ratio = 0.2,
        panel.grid = element_blank(), legend.position = "none")

pdf("./Revision_R_codes/008_fiber_seq//rplots/fiber.ov.pdf", width=15, height=8, useDingbats=FALSE)
ROI.WT.fiber.plot
dev.off()




